import { Campaign, Creative, CampaignMetrics, CreativeMetrics } from "./types";

export const mockCampaigns: Campaign[] = [
  {
    id: "camp_1",
    name: "Summer Sale 2024",
    description: "Promoting summer collection with 20% discount",
    platform: "META",
    status: "ACTIVE",
    objective: "CONVERSIONS",
    budget: 5000,
    dailyBudget: 200,
    spent: 3245.50,
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    siteId: "site_1",
    site: { id: "site_1", name: "Luxe Home Decor" },
    metrics: {
      impressions: 245000,
      clicks: 4900,
      conversions: 147,
      spend: 3245.50,
      revenue: 12680.00,
      ctr: 2.0,
      cpc: 0.66,
      cpm: 13.25,
      roas: 3.91,
    },
    creativesCount: 8,
    createdAt: new Date("2024-02-25"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "camp_2",
    name: "Brand Awareness - Fitness",
    description: "Building brand awareness for FitGear Pro",
    platform: "META",
    status: "ACTIVE",
    objective: "AWARENESS",
    budget: 3000,
    dailyBudget: 150,
    spent: 1890.25,
    startDate: new Date("2024-03-05"),
    endDate: new Date("2024-04-05"),
    siteId: "site_2",
    site: { id: "site_2", name: "FitGear Pro" },
    metrics: {
      impressions: 520000,
      clicks: 7800,
      conversions: 89,
      spend: 1890.25,
      revenue: 5670.00,
      ctr: 1.5,
      cpc: 0.24,
      cpm: 3.64,
      roas: 3.0,
    },
    creativesCount: 12,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "camp_3",
    name: "Google Shopping - Beauty",
    description: "Product listing ads for organic beauty products",
    platform: "GOOGLE",
    status: "ACTIVE",
    objective: "SALES",
    budget: 4000,
    dailyBudget: 180,
    spent: 2567.80,
    startDate: new Date("2024-02-15"),
    endDate: null,
    siteId: "site_3",
    site: { id: "site_3", name: "Organic Beauty Co" },
    metrics: {
      impressions: 180000,
      clicks: 3600,
      conversions: 216,
      spend: 2567.80,
      revenue: 8450.00,
      ctr: 2.0,
      cpc: 0.71,
      cpm: 14.27,
      roas: 3.29,
    },
    creativesCount: 5,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "camp_4",
    name: "TikTok Tech Launch",
    description: "New product launch campaign for tech gadgets",
    platform: "TIKTOK",
    status: "PAUSED",
    objective: "TRAFFIC",
    budget: 2500,
    dailyBudget: 125,
    spent: 1234.00,
    startDate: new Date("2024-03-10"),
    endDate: new Date("2024-03-25"),
    siteId: "site_4",
    site: { id: "site_4", name: "TechHub Gadgets" },
    metrics: {
      impressions: 890000,
      clicks: 12460,
      conversions: 67,
      spend: 1234.00,
      revenue: 4560.00,
      ctr: 1.4,
      cpc: 0.10,
      cpm: 1.39,
      roas: 3.70,
    },
    creativesCount: 15,
    createdAt: new Date("2024-03-08"),
    updatedAt: new Date("2024-03-18"),
  },
  {
    id: "camp_5",
    name: "Retargeting - Home Decor",
    description: "Retargeting website visitors who abandoned cart",
    platform: "META",
    status: "ACTIVE",
    objective: "CONVERSIONS",
    budget: 1500,
    dailyBudget: 75,
    spent: 892.30,
    startDate: new Date("2024-03-01"),
    endDate: null,
    siteId: "site_1",
    site: { id: "site_1", name: "Luxe Home Decor" },
    metrics: {
      impressions: 45000,
      clicks: 1350,
      conversions: 54,
      spend: 892.30,
      revenue: 6780.00,
      ctr: 3.0,
      cpc: 0.66,
      cpm: 19.83,
      roas: 7.60,
    },
    creativesCount: 4,
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "camp_6",
    name: "Pinterest Inspiration",
    description: "Lifestyle content for home decor inspiration",
    platform: "PINTEREST",
    status: "DRAFT",
    objective: "AWARENESS",
    budget: 2000,
    dailyBudget: 100,
    spent: 0,
    startDate: null,
    endDate: null,
    siteId: "site_1",
    site: { id: "site_1", name: "Luxe Home Decor" },
    metrics: null,
    creativesCount: 0,
    createdAt: new Date("2024-03-19"),
    updatedAt: new Date("2024-03-19"),
  },
];

export const mockCreatives: Creative[] = [
  {
    id: "cre_1",
    name: "Summer Collection Hero",
    type: "IMAGE",
    status: "ACTIVE",
    headline: "Transform Your Space This Summer",
    description: "Shop our curated summer collection with 20% off all items",
    callToAction: "Shop Now",
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
    videoUrl: null,
    thumbnailUrl: null,
    siteId: "site_1",
    site: { id: "site_1", name: "Luxe Home Decor" },
    campaignId: "camp_1",
    campaign: { id: "camp_1", name: "Summer Sale 2024" },
    metrics: {
      impressions: 89000,
      clicks: 2136,
      conversions: 64,
      spend: 1245.50,
      ctr: 2.4,
      cvr: 3.0,
    },
    createdAt: new Date("2024-02-25"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "cre_2",
    name: "Living Room Makeover Video",
    type: "VIDEO",
    status: "ACTIVE",
    headline: "Your Dream Living Room Awaits",
    description: "See how easy it is to transform your space",
    callToAction: "Learn More",
    imageUrl: null,
    videoUrl: "https://example.com/video1.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
    siteId: "site_1",
    site: { id: "site_1", name: "Luxe Home Decor" },
    campaignId: "camp_1",
    campaign: { id: "camp_1", name: "Summer Sale 2024" },
    metrics: {
      impressions: 67000,
      clicks: 1340,
      conversions: 40,
      spend: 980.25,
      ctr: 2.0,
      cvr: 2.99,
    },
    createdAt: new Date("2024-02-26"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "cre_3",
    name: "Fitness Journey UGC",
    type: "UGC",
    status: "ACTIVE",
    headline: "Real Results from Real People",
    description: "Join thousands who transformed their fitness with FitGear",
    callToAction: "Get Started",
    imageUrl: null,
    videoUrl: "https://example.com/ugc1.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48",
    siteId: "site_2",
    site: { id: "site_2", name: "FitGear Pro" },
    campaignId: "camp_2",
    campaign: { id: "camp_2", name: "Brand Awareness - Fitness" },
    metrics: {
      impressions: 234000,
      clicks: 4680,
      conversions: 56,
      spend: 890.50,
      ctr: 2.0,
      cvr: 1.2,
    },
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "cre_4",
    name: "Skincare Routine Carousel",
    type: "CAROUSEL",
    status: "ACTIVE",
    headline: "Your 5-Step Natural Skincare Routine",
    description: "Discover our bestselling organic products",
    callToAction: "Shop Collection",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03",
    videoUrl: null,
    thumbnailUrl: null,
    siteId: "site_3",
    site: { id: "site_3", name: "Organic Beauty Co" },
    campaignId: "camp_3",
    campaign: { id: "camp_3", name: "Google Shopping - Beauty" },
    metrics: {
      impressions: 78000,
      clicks: 1950,
      conversions: 117,
      spend: 1234.50,
      ctr: 2.5,
      cvr: 6.0,
    },
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "cre_5",
    name: "Tech Unboxing Video",
    type: "VIDEO",
    status: "PAUSED",
    headline: "Unbox the Future",
    description: "See what's inside our latest tech drops",
    callToAction: "Pre-Order Now",
    imageUrl: null,
    videoUrl: "https://example.com/tech-unboxing.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece",
    siteId: "site_4",
    site: { id: "site_4", name: "TechHub Gadgets" },
    campaignId: "camp_4",
    campaign: { id: "camp_4", name: "TikTok Tech Launch" },
    metrics: {
      impressions: 456000,
      clicks: 6384,
      conversions: 34,
      spend: 612.00,
      ctr: 1.4,
      cvr: 0.53,
    },
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-18"),
  },
];

export function getCampaignsBySiteId(siteId: string): Campaign[] {
  return mockCampaigns.filter(c => c.siteId === siteId);
}

export function getCampaignById(id: string): Campaign | undefined {
  return mockCampaigns.find(c => c.id === id);
}

export function getCreativesBySiteId(siteId: string): Creative[] {
  return mockCreatives.filter(c => c.siteId === siteId);
}

export function getCreativesByCampaignId(campaignId: string): Creative[] {
  return mockCreatives.filter(c => c.campaignId === campaignId);
}

export function getCreativeById(id: string): Creative | undefined {
  return mockCreatives.find(c => c.id === id);
}

export function getAdsSummary() {
  const activeCampaigns = mockCampaigns.filter(c => c.status === "ACTIVE").length;
  const totalSpend = mockCampaigns.reduce((sum, c) => sum + c.spent, 0);
  const totalRevenue = mockCampaigns.reduce((sum, c) => sum + (c.metrics?.revenue || 0), 0);
  const totalImpressions = mockCampaigns.reduce((sum, c) => sum + (c.metrics?.impressions || 0), 0);
  const totalConversions = mockCampaigns.reduce((sum, c) => sum + (c.metrics?.conversions || 0), 0);
  const avgRoas = totalSpend > 0 ? totalRevenue / totalSpend : 0;

  return {
    totalCampaigns: mockCampaigns.length,
    activeCampaigns,
    totalSpend,
    totalRevenue,
    totalImpressions,
    totalConversions,
    avgRoas,
    totalCreatives: mockCreatives.length,
  };
}
