import { ProductListing, ProductSuggestion } from "./types";

export const mockProducts: ProductListing[] = [
  {
    id: "prod_1",
    siteId: "site_1",
    site: { id: "site_1", name: "Luxe Home Decor" },
    externalId: "shopify_7890123",
    title: "Velvet Accent Chair - Emerald Green",
    description: "Luxurious velvet accent chair with gold-finished metal legs. Perfect for adding a touch of elegance to any living space.",
    price: 549.99,
    compareAtPrice: 699.99,
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
    images: [],
    category: "Living Room",
    tags: ["chair", "velvet", "accent", "green"],
    inventory: 24,
    sku: "LHD-CHAIR-001",
    status: "ACTIVE",
    seoTitle: "Emerald Green Velvet Accent Chair | Luxe Home Decor",
    seoDescription: "Shop our luxurious emerald green velvet accent chair with gold-finished legs.",
    optimizationScore: 85,
    optimizationSuggestions: [
      {
        id: "sug_1",
        type: "description",
        priority: "medium",
        suggestion: "Add dimensions and material details to the description",
        currentValue: null,
        suggestedValue: "Include: Dimensions (32\"W x 30\"D x 34\"H), Weight capacity, Care instructions",
      },
    ],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-03-18"),
  },
  {
    id: "prod_2",
    siteId: "site_1",
    site: { id: "site_1", name: "Luxe Home Decor" },
    externalId: "shopify_7890124",
    title: "Abstract Wall Art Set - 3 Pieces",
    description: "Modern abstract wall art set featuring bold geometric patterns.",
    price: 189.99,
    compareAtPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    images: [],
    category: "Wall Decor",
    tags: ["wall art", "abstract", "modern", "set"],
    inventory: 45,
    sku: "LHD-ART-002",
    status: "ACTIVE",
    seoTitle: null,
    seoDescription: null,
    optimizationScore: 62,
    optimizationSuggestions: [
      {
        id: "sug_2",
        type: "seo",
        priority: "high",
        suggestion: "Add SEO title and meta description",
        currentValue: null,
        suggestedValue: "Modern Abstract Wall Art Set of 3 | Geometric Art | Luxe Home Decor",
      },
      {
        id: "sug_3",
        type: "description",
        priority: "medium",
        suggestion: "Expand description with size options and hanging instructions",
        currentValue: "Modern abstract wall art set featuring bold geometric patterns.",
        suggestedValue: "Transform your space with this stunning 3-piece abstract wall art set. Featuring bold geometric patterns in contemporary colors, each canvas measures 16\"x20\". Easy-hang system included.",
      },
    ],
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: "prod_3",
    siteId: "site_2",
    site: { id: "site_2", name: "FitGear Pro" },
    externalId: "shopify_4560789",
    title: "Professional Resistance Bands Set",
    description: "Complete resistance bands set with 5 different resistance levels. Includes door anchor, handles, and carrying bag. Perfect for home workouts.",
    price: 39.99,
    compareAtPrice: 54.99,
    imageUrl: "https://images.unsplash.com/photo-1598289431512-b97b0917affc",
    images: [],
    category: "Equipment",
    tags: ["resistance bands", "home workout", "fitness", "strength"],
    inventory: 234,
    sku: "FGP-BAND-001",
    status: "ACTIVE",
    seoTitle: "Professional Resistance Bands Set | 5 Levels | FitGear Pro",
    seoDescription: "Get stronger at home with our professional resistance bands set. 5 resistance levels included.",
    optimizationScore: 92,
    optimizationSuggestions: [],
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-03-19"),
  },
  {
    id: "prod_4",
    siteId: "site_2",
    site: { id: "site_2", name: "FitGear Pro" },
    externalId: "shopify_4560790",
    title: "Premium Yoga Mat - 6mm",
    description: "Non-slip premium yoga mat with alignment lines.",
    price: 49.99,
    compareAtPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f",
    images: [],
    category: "Yoga",
    tags: ["yoga mat", "yoga", "pilates", "fitness"],
    inventory: 156,
    sku: "FGP-YOGA-001",
    status: "ACTIVE",
    seoTitle: null,
    seoDescription: null,
    optimizationScore: 58,
    optimizationSuggestions: [
      {
        id: "sug_4",
        type: "seo",
        priority: "high",
        suggestion: "Add SEO metadata",
        currentValue: null,
        suggestedValue: "Premium Non-Slip Yoga Mat 6mm | Alignment Lines | FitGear Pro",
      },
      {
        id: "sug_5",
        type: "description",
        priority: "high",
        suggestion: "Expand product description significantly",
        currentValue: "Non-slip premium yoga mat with alignment lines.",
        suggestedValue: "Elevate your practice with our premium 6mm yoga mat. Features: Non-slip TPE surface, alignment guide lines, extra cushioning for joints, eco-friendly materials. Dimensions: 72\" x 26\". Includes carrying strap.",
      },
    ],
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-03-12"),
  },
  {
    id: "prod_5",
    siteId: "site_3",
    site: { id: "site_3", name: "Organic Beauty Co" },
    externalId: "shopify_1234567",
    title: "Hydrating Face Serum with Hyaluronic Acid",
    description: "Our bestselling hydrating serum combines triple-weight hyaluronic acid with organic aloe vera for deep, lasting hydration. Suitable for all skin types. 100% vegan and cruelty-free.",
    price: 45.00,
    compareAtPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be",
    images: [],
    category: "Skincare",
    tags: ["serum", "hydrating", "hyaluronic acid", "vegan"],
    inventory: 312,
    sku: "OBC-SER-001",
    status: "ACTIVE",
    seoTitle: "Organic Hydrating Face Serum | Hyaluronic Acid | Organic Beauty Co",
    seoDescription: "Deep hydration with our organic face serum. Triple-weight hyaluronic acid + aloe vera. 100% vegan.",
    optimizationScore: 95,
    optimizationSuggestions: [],
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "prod_6",
    siteId: "site_3",
    site: { id: "site_3", name: "Organic Beauty Co" },
    externalId: "shopify_1234568",
    title: "Vitamin C Brightening Cream",
    description: "Brighten your skin with our vitamin C cream.",
    price: 38.00,
    compareAtPrice: 48.00,
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03",
    images: [],
    category: "Skincare",
    tags: ["cream", "vitamin c", "brightening", "moisturizer"],
    inventory: 189,
    sku: "OBC-CRM-002",
    status: "ACTIVE",
    seoTitle: null,
    seoDescription: null,
    optimizationScore: 52,
    optimizationSuggestions: [
      {
        id: "sug_6",
        type: "description",
        priority: "high",
        suggestion: "Product description is too short and generic",
        currentValue: "Brighten your skin with our vitamin C cream.",
        suggestedValue: "Reveal radiant, even-toned skin with our powerful Vitamin C Brightening Cream. Formulated with 15% stabilized vitamin C, niacinamide, and organic jojoba oil. Reduces dark spots, boosts collagen production, and protects against environmental damage. 50ml / 1.7 oz.",
      },
      {
        id: "sug_7",
        type: "seo",
        priority: "high",
        suggestion: "Missing SEO metadata",
        currentValue: null,
        suggestedValue: "Vitamin C Brightening Cream | Dark Spot Corrector | Organic Beauty Co",
      },
    ],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-08"),
  },
  {
    id: "prod_7",
    siteId: "site_4",
    site: { id: "site_4", name: "TechHub Gadgets" },
    externalId: "shopify_9876543",
    title: "Wireless Earbuds Pro - Active Noise Cancellation",
    description: "Experience premium sound with our Wireless Earbuds Pro. Features include active noise cancellation, 30-hour battery life with case, and IPX5 water resistance.",
    price: 129.99,
    compareAtPrice: 159.99,
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df",
    images: [],
    category: "Audio",
    tags: ["earbuds", "wireless", "anc", "bluetooth"],
    inventory: 78,
    sku: "THG-EAR-001",
    status: "ACTIVE",
    seoTitle: "Wireless Earbuds Pro with ANC | 30hr Battery | TechHub",
    seoDescription: "Premium wireless earbuds with active noise cancellation, 30-hour battery, and IPX5 water resistance.",
    optimizationScore: 88,
    optimizationSuggestions: [
      {
        id: "sug_8",
        type: "image",
        priority: "medium",
        suggestion: "Add more product images showing different angles and use cases",
        currentValue: "1 image",
        suggestedValue: "Add 4-5 images: front view, case, wearing demo, size comparison",
      },
    ],
    createdAt: new Date("2023-12-10"),
    updatedAt: new Date("2024-03-18"),
  },
  {
    id: "prod_8",
    siteId: "site_4",
    site: { id: "site_4", name: "TechHub Gadgets" },
    externalId: "shopify_9876544",
    title: "Fast Wireless Charger Pad",
    description: "15W fast wireless charger.",
    price: 24.99,
    compareAtPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1586495777744-4413f21062fa",
    images: [],
    category: "Accessories",
    tags: ["charger", "wireless", "fast charging"],
    inventory: 0,
    sku: "THG-CHG-002",
    status: "OUT_OF_STOCK",
    seoTitle: null,
    seoDescription: null,
    optimizationScore: 35,
    optimizationSuggestions: [
      {
        id: "sug_9",
        type: "description",
        priority: "high",
        suggestion: "Product description is extremely minimal",
        currentValue: "15W fast wireless charger.",
        suggestedValue: "Power up your devices in no time with our 15W Fast Wireless Charger Pad. Compatible with all Qi-enabled devices including iPhone 14/13/12 and Samsung Galaxy. Features LED indicator, foreign object detection, and over-temperature protection. Sleek, slim design fits any space.",
      },
      {
        id: "sug_10",
        type: "seo",
        priority: "high",
        suggestion: "Add SEO title and description",
        currentValue: null,
        suggestedValue: "15W Fast Wireless Charger | Qi Compatible | TechHub Gadgets",
      },
      {
        id: "sug_11",
        type: "pricing",
        priority: "medium",
        suggestion: "Consider adding a compare-at price to show value",
        currentValue: null,
        suggestedValue: "Compare at: $34.99",
      },
    ],
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-03-05"),
  },
  {
    id: "prod_9",
    siteId: "site_5",
    site: { id: "site_5", name: "Pet Paradise" },
    externalId: "shopify_5678901",
    title: "Interactive Dog Puzzle Toy",
    description: "Keep your pup entertained and mentally stimulated with our interactive puzzle toy. Multiple difficulty levels to challenge dogs of all ages.",
    price: 19.99,
    compareAtPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1535294435445-d7249524ef2e",
    images: [],
    category: "Dog Toys",
    tags: ["dog toy", "puzzle", "interactive", "mental stimulation"],
    inventory: 67,
    sku: "PP-TOY-001",
    status: "ACTIVE",
    seoTitle: "Interactive Dog Puzzle Toy | Mental Stimulation | Pet Paradise",
    seoDescription: "Challenge your dog with our interactive puzzle toy. Multiple difficulty levels for all ages.",
    optimizationScore: 78,
    optimizationSuggestions: [
      {
        id: "sug_12",
        type: "description",
        priority: "low",
        suggestion: "Add size/breed recommendations",
        currentValue: null,
        suggestedValue: "Add: \"Best for small to medium dogs. Measures 10\" x 10\".",
      },
    ],
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "prod_10",
    siteId: "site_5",
    site: { id: "site_5", name: "Pet Paradise" },
    externalId: "shopify_5678902",
    title: "Premium Cat Tree - 5 Levels",
    description: "Deluxe cat tree with 5 platforms.",
    price: 89.99,
    compareAtPrice: 119.99,
    imageUrl: "https://images.unsplash.com/photo-1545249390-6bdfa286032f",
    images: [],
    category: "Cat Furniture",
    tags: ["cat tree", "scratching post", "cat furniture"],
    inventory: 12,
    sku: "PP-CAT-002",
    status: "ACTIVE",
    seoTitle: null,
    seoDescription: null,
    optimizationScore: 45,
    optimizationSuggestions: [
      {
        id: "sug_13",
        type: "description",
        priority: "high",
        suggestion: "Description lacks key details buyers need",
        currentValue: "Deluxe cat tree with 5 platforms.",
        suggestedValue: "Give your feline friend the ultimate playground with our Premium 5-Level Cat Tree. Features include: 5 spacious platforms, 2 cozy hideaway condos, sisal-wrapped scratching posts, and dangling toy balls. Sturdy base prevents tipping. Dimensions: 24\"W x 20\"D x 60\"H. Supports cats up to 20 lbs per platform.",
      },
      {
        id: "sug_14",
        type: "seo",
        priority: "high",
        suggestion: "Missing SEO optimization",
        currentValue: null,
        suggestedValue: "5-Level Premium Cat Tree | Scratching Posts & Condos | Pet Paradise",
      },
    ],
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-03-10"),
  },
];

export function getProductsBySiteId(siteId: string): ProductListing[] {
  return mockProducts.filter(p => p.siteId === siteId);
}

export function getProductById(id: string): ProductListing | undefined {
  return mockProducts.find(p => p.id === id);
}

export function getProductsSummary() {
  const totalProducts = mockProducts.length;
  const activeProducts = mockProducts.filter(p => p.status === "ACTIVE").length;
  const outOfStock = mockProducts.filter(p => p.status === "OUT_OF_STOCK").length;
  const avgOptimizationScore = mockProducts.reduce((sum, p) => sum + p.optimizationScore, 0) / totalProducts;
  const productsNeedingOptimization = mockProducts.filter(p => p.optimizationScore < 70).length;
  const totalInventory = mockProducts.reduce((sum, p) => sum + p.inventory, 0);

  return {
    totalProducts,
    activeProducts,
    outOfStock,
    avgOptimizationScore: Math.round(avgOptimizationScore),
    productsNeedingOptimization,
    totalInventory,
  };
}
