import { SEOAnalysis, SEOKeyword, SEOIssue, SEORecommendation } from "./types";

export const mockSEOAnalyses: SEOAnalysis[] = [
  {
    id: "seo_1",
    siteId: "site_1",
    site: { id: "site_1", name: "Luxe Home Decor", domain: "luxehomedecor.com" },
    overallScore: 78,
    technicalScore: 85,
    onPageScore: 72,
    contentScore: 80,
    backlinksScore: 74,
    totalKeywords: 245,
    keywordsTop10: 23,
    keywordsTop100: 89,
    organicTraffic: 18500,
    backlinksCount: 1240,
    domainAuthority: 42,
    issues: [
      {
        id: "issue_1",
        severity: "critical",
        category: "technical",
        title: "Missing SSL on 3 pages",
        description: "Some pages are still accessible via HTTP, which affects security and rankings",
        affectedPages: 3,
      },
      {
        id: "issue_2",
        severity: "warning",
        category: "content",
        title: "Duplicate meta descriptions",
        description: "15 pages share identical meta descriptions",
        affectedPages: 15,
      },
      {
        id: "issue_3",
        severity: "warning",
        category: "performance",
        title: "Slow page load time",
        description: "Average page load time is 4.2s, recommended is under 3s",
        affectedPages: 0,
      },
      {
        id: "issue_4",
        severity: "info",
        category: "mobile",
        title: "Mobile viewport issues",
        description: "Some elements extend beyond mobile viewport",
        affectedPages: 8,
      },
    ],
    recommendations: [
      {
        id: "rec_1",
        priority: "high",
        category: "technical",
        title: "Implement HTTPS redirect",
        description: "Set up 301 redirects from HTTP to HTTPS for all pages",
        impact: "High - Improves security signals and user trust",
        effort: "Low - Can be done via server config",
      },
      {
        id: "rec_2",
        priority: "high",
        category: "content",
        title: "Optimize product descriptions",
        description: "Add unique, keyword-rich descriptions to product pages",
        impact: "High - Can improve rankings for product keywords",
        effort: "Medium - Requires content creation",
      },
      {
        id: "rec_3",
        priority: "medium",
        category: "backlinks",
        title: "Build quality backlinks",
        description: "Focus on getting links from home decor blogs and magazines",
        impact: "High - Will improve domain authority",
        effort: "High - Requires outreach strategy",
      },
    ],
    keywords: [
      { id: "kw_1", keyword: "luxury home decor", position: 5, previousPosition: 8, change: 3, searchVolume: 8100, difficulty: 65, url: "/collections/luxury" },
      { id: "kw_2", keyword: "modern furniture", position: 12, previousPosition: 15, change: 3, searchVolume: 22000, difficulty: 78, url: "/collections/modern" },
      { id: "kw_3", keyword: "home accessories", position: 8, previousPosition: 6, change: -2, searchVolume: 14800, difficulty: 55, url: "/collections/accessories" },
      { id: "kw_4", keyword: "designer throw pillows", position: 3, previousPosition: 4, change: 1, searchVolume: 2400, difficulty: 42, url: "/products/throw-pillows" },
      { id: "kw_5", keyword: "wall art prints", position: 18, previousPosition: 22, change: 4, searchVolume: 18100, difficulty: 68, url: "/collections/wall-art" },
    ],
    analyzedAt: new Date("2024-03-19"),
    createdAt: new Date("2024-03-19"),
    updatedAt: new Date("2024-03-19"),
  },
  {
    id: "seo_2",
    siteId: "site_2",
    site: { id: "site_2", name: "FitGear Pro", domain: "fitgearpro.com" },
    overallScore: 82,
    technicalScore: 88,
    onPageScore: 79,
    contentScore: 84,
    backlinksScore: 76,
    totalKeywords: 312,
    keywordsTop10: 34,
    keywordsTop100: 124,
    organicTraffic: 28400,
    backlinksCount: 2150,
    domainAuthority: 48,
    issues: [
      {
        id: "issue_5",
        severity: "warning",
        category: "content",
        title: "Thin content on category pages",
        description: "Category pages have less than 300 words of content",
        affectedPages: 8,
      },
      {
        id: "issue_6",
        severity: "info",
        category: "technical",
        title: "Missing alt tags",
        description: "Some product images are missing alt text",
        affectedPages: 24,
      },
    ],
    recommendations: [
      {
        id: "rec_4",
        priority: "high",
        category: "content",
        title: "Add content to category pages",
        description: "Write descriptive content for each product category",
        impact: "High - Can rank for broader category keywords",
        effort: "Medium - Requires content writing",
      },
      {
        id: "rec_5",
        priority: "medium",
        category: "keywords",
        title: "Target long-tail fitness keywords",
        description: "Create content targeting specific fitness equipment queries",
        impact: "Medium - Less competition, qualified traffic",
        effort: "Medium - Requires keyword research and content",
      },
    ],
    keywords: [
      { id: "kw_6", keyword: "home gym equipment", position: 7, previousPosition: 9, change: 2, searchVolume: 33100, difficulty: 72, url: "/collections/home-gym" },
      { id: "kw_7", keyword: "resistance bands set", position: 4, previousPosition: 5, change: 1, searchVolume: 18100, difficulty: 58, url: "/products/resistance-bands" },
      { id: "kw_8", keyword: "workout clothes men", position: 15, previousPosition: 18, change: 3, searchVolume: 27100, difficulty: 68, url: "/collections/mens" },
      { id: "kw_9", keyword: "yoga mat premium", position: 6, previousPosition: 8, change: 2, searchVolume: 9900, difficulty: 45, url: "/products/yoga-mat" },
    ],
    analyzedAt: new Date("2024-03-19"),
    createdAt: new Date("2024-03-19"),
    updatedAt: new Date("2024-03-19"),
  },
  {
    id: "seo_3",
    siteId: "site_3",
    site: { id: "site_3", name: "Organic Beauty Co", domain: "organicbeautyco.com" },
    overallScore: 85,
    technicalScore: 90,
    onPageScore: 84,
    contentScore: 88,
    backlinksScore: 78,
    totalKeywords: 278,
    keywordsTop10: 42,
    keywordsTop100: 145,
    organicTraffic: 22100,
    backlinksCount: 1890,
    domainAuthority: 45,
    issues: [
      {
        id: "issue_7",
        severity: "info",
        category: "performance",
        title: "Large image files",
        description: "Some product images exceed 500KB",
        affectedPages: 12,
      },
    ],
    recommendations: [
      {
        id: "rec_6",
        priority: "medium",
        category: "technical",
        title: "Optimize image sizes",
        description: "Compress images and use WebP format",
        impact: "Medium - Improves page speed",
        effort: "Low - Can be automated",
      },
      {
        id: "rec_7",
        priority: "high",
        category: "content",
        title: "Create ingredient guides",
        description: "Develop educational content about natural ingredients",
        impact: "High - Builds authority and attracts links",
        effort: "High - Requires research and writing",
      },
    ],
    keywords: [
      { id: "kw_10", keyword: "organic skincare", position: 4, previousPosition: 6, change: 2, searchVolume: 22200, difficulty: 62, url: "/collections/skincare" },
      { id: "kw_11", keyword: "natural face cream", position: 3, previousPosition: 3, change: 0, searchVolume: 12100, difficulty: 55, url: "/products/face-cream" },
      { id: "kw_12", keyword: "vegan beauty products", position: 8, previousPosition: 12, change: 4, searchVolume: 8100, difficulty: 48, url: "/collections/vegan" },
      { id: "kw_13", keyword: "clean beauty brands", position: 11, previousPosition: 14, change: 3, searchVolume: 14800, difficulty: 58, url: "/" },
    ],
    analyzedAt: new Date("2024-03-18"),
    createdAt: new Date("2024-03-18"),
    updatedAt: new Date("2024-03-18"),
  },
  {
    id: "seo_4",
    siteId: "site_4",
    site: { id: "site_4", name: "TechHub Gadgets", domain: "techhubgadgets.com" },
    overallScore: 71,
    technicalScore: 82,
    onPageScore: 68,
    contentScore: 65,
    backlinksScore: 70,
    totalKeywords: 198,
    keywordsTop10: 15,
    keywordsTop100: 67,
    organicTraffic: 34200,
    backlinksCount: 890,
    domainAuthority: 38,
    issues: [
      {
        id: "issue_8",
        severity: "critical",
        category: "content",
        title: "Product pages lack unique content",
        description: "Many product descriptions are copied from manufacturers",
        affectedPages: 45,
      },
      {
        id: "issue_9",
        severity: "warning",
        category: "technical",
        title: "Broken internal links",
        description: "Several internal links point to 404 pages",
        affectedPages: 7,
      },
    ],
    recommendations: [
      {
        id: "rec_8",
        priority: "high",
        category: "content",
        title: "Rewrite product descriptions",
        description: "Create unique, detailed descriptions for all products",
        impact: "High - Avoid duplicate content penalties",
        effort: "High - Significant content effort",
      },
      {
        id: "rec_9",
        priority: "high",
        category: "technical",
        title: "Fix broken links",
        description: "Update or remove broken internal links",
        impact: "Medium - Improves crawlability",
        effort: "Low - Quick technical fix",
      },
    ],
    keywords: [
      { id: "kw_14", keyword: "tech gadgets 2024", position: 22, previousPosition: 28, change: 6, searchVolume: 18100, difficulty: 72, url: "/collections/new" },
      { id: "kw_15", keyword: "wireless earbuds", position: 45, previousPosition: 52, change: 7, searchVolume: 135000, difficulty: 85, url: "/products/earbuds" },
      { id: "kw_16", keyword: "phone accessories", position: 18, previousPosition: 20, change: 2, searchVolume: 49500, difficulty: 75, url: "/collections/phone" },
    ],
    analyzedAt: new Date("2024-03-17"),
    createdAt: new Date("2024-03-17"),
    updatedAt: new Date("2024-03-17"),
  },
  {
    id: "seo_5",
    siteId: "site_5",
    site: { id: "site_5", name: "Pet Paradise", domain: "petparadiseshop.com" },
    overallScore: 68,
    technicalScore: 75,
    onPageScore: 65,
    contentScore: 70,
    backlinksScore: 62,
    totalKeywords: 156,
    keywordsTop10: 8,
    keywordsTop100: 42,
    organicTraffic: 8900,
    backlinksCount: 420,
    domainAuthority: 28,
    issues: [
      {
        id: "issue_10",
        severity: "warning",
        category: "technical",
        title: "Slow server response time",
        description: "TTFB averages 1.8 seconds",
        affectedPages: 0,
      },
      {
        id: "issue_11",
        severity: "warning",
        category: "content",
        title: "Missing blog content",
        description: "No blog section to target informational queries",
        affectedPages: 0,
      },
    ],
    recommendations: [
      {
        id: "rec_10",
        priority: "high",
        category: "technical",
        title: "Improve server performance",
        description: "Upgrade hosting or implement caching",
        impact: "High - Affects all rankings",
        effort: "Medium - May require hosting changes",
      },
      {
        id: "rec_11",
        priority: "medium",
        category: "content",
        title: "Start a pet care blog",
        description: "Create educational content about pet care",
        impact: "High - Attracts organic traffic",
        effort: "High - Ongoing content creation",
      },
    ],
    keywords: [
      { id: "kw_17", keyword: "pet supplies online", position: 34, previousPosition: 38, change: 4, searchVolume: 22200, difficulty: 68, url: "/" },
      { id: "kw_18", keyword: "dog toys", position: 28, previousPosition: 30, change: 2, searchVolume: 74000, difficulty: 72, url: "/collections/dog-toys" },
      { id: "kw_19", keyword: "cat accessories", position: 42, previousPosition: 48, change: 6, searchVolume: 18100, difficulty: 58, url: "/collections/cat" },
    ],
    analyzedAt: new Date("2024-03-15"),
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
  },
];

export function getSEOAnalysisBySiteId(siteId: string): SEOAnalysis | undefined {
  return mockSEOAnalyses.find(s => s.siteId === siteId);
}

export function getSEOAnalysisById(id: string): SEOAnalysis | undefined {
  return mockSEOAnalyses.find(s => s.id === id);
}

export function getSEOSummary() {
  const avgScore = mockSEOAnalyses.reduce((sum, s) => sum + s.overallScore, 0) / mockSEOAnalyses.length;
  const totalKeywords = mockSEOAnalyses.reduce((sum, s) => sum + s.totalKeywords, 0);
  const totalKeywordsTop10 = mockSEOAnalyses.reduce((sum, s) => sum + s.keywordsTop10, 0);
  const totalOrganicTraffic = mockSEOAnalyses.reduce((sum, s) => sum + s.organicTraffic, 0);
  const totalBacklinks = mockSEOAnalyses.reduce((sum, s) => sum + s.backlinksCount, 0);
  const totalCriticalIssues = mockSEOAnalyses.reduce(
    (sum, s) => sum + s.issues.filter(i => i.severity === "critical").length,
    0
  );

  return {
    avgScore: Math.round(avgScore),
    totalKeywords,
    totalKeywordsTop10,
    totalOrganicTraffic,
    totalBacklinks,
    totalCriticalIssues,
    sitesAnalyzed: mockSEOAnalyses.length,
  };
}
